model: 'logistic' # 'logistic' 'LSTM' 'svm' 'NN'
nmbr_of_runs: 10

logistic:
  data_path: 'processed_data_features.pkl'
  seed: 4
  print: True

svm:
  data_path: 'processed_data_features.pkl'
  seed: 4
  print: True

NN:
  epochs: 10
  lr: 0.0001
  solver: 'adam'
  batch_size: 9
  hidden: 64
  layers: 2
  in_dim: 30
  out_dim: 10
  max_norm: 5
  device: 'cpu'
  seed: 4
  data_path: 'processed_data_features.pkl'
  print: True

LSTM:
  epochs: 10
  lr: 0.001
  solver: 'adam'
  batch_size: 9
  hidden: 64
  layers: 2
  in_dim: 17  # 68, 17
  out_dim: 10
  max_norm: 5
  device: 'cpu'
  seed: 4
  data_path: 'processed_data_temporal.pkl'
  print: True

dataset:
  path: './dataset_mood_smartphone.csv'
  save_panda: True
  temporal: False
  window: 5
  tsfresh_features: 'minimal'  # 'minimal', 'efficient', 'comprehensive'
  columns: ['mood', 'circumplex.valence']
