models: ['baseline', 'linear', 'svm', 'random_forest', 'NN', 'LSTM', 'BiLSTM']  # 'linear' 'LSTM' 'BiLSTM' 'svm' 'NN' 'random_forest' 'baseline'
nmbr_of_runs: 1  # 'baseline', 'linear', 'svm', 'random_forest', 'NN', 'LSTM',
print: False

baseline:
  data_path: './data_processed/processed_data_advanced.pkl'
  targets_path: './data_processed/baseline_targets.pkl'
  seed: 4
  print: True

random_forest:
  data_path: './data_processed/processed_data_advanced.pkl'
  seed: 4
  print: True

linear:
  data_path: './data_processed/processed_data_advanced.pkl'
  seed: 4
  print: True

svm:
  data_path: './data_processed/processed_data_advanced.pkl'
  seed: 4
  print: True

NN:
  epochs: 10
  lr: 0.01
  momentum: 0.1
  batch_size: 32
  in_dim: 1623
  out_dim: 1
  max_norm: 5
  device: 'cuda'  # cuda, cpu
  seed: 4
  data_path: './data_processed/processed_data_advanced.pkl'
  print_every: 10
  print: True

LSTM:
  epochs: 10
  lr: 0.05
  momentum: 0.5
  batch_size: 1  # This needs to be 1 because of the variable sequence lengths
  hidden: 64
  layers: 2
  in_dim: 43
  out_dim: 1
  max_norm: 5
  device: 'cuda'  # cuda, cpu
  seed: 4
  data_path: './data_processed/processed_data_basic.pkl'
  print_every: 10
  print: True

BiLSTM:
  epochs: 10
  lr: 0.05
  momentum: 0.5
  batch_size: 1  # This needs to be 1 because of the variable sequence lengths
  hidden: 64
  layers: 2
  in_dim: 43
  out_dim: 1
  max_norm: 5
  device: 'cuda'  # cuda, cpu
  seed: 4
  data_path: './data_processed/processed_data_basic.pkl'
  print_every: 10
  print: True

dataset:
  path: './data_raw/dataset_mood_smartphone.csv'
  save_folder: 'data_processed'
  save_panda: True
  window: 5
  tsfresh_features: 'comprehensive'  # 'minimal', 'efficient', 'comprehensive'
  columns: ['mood', 'circumplex.valence']
  standard: True
  exclude_norm: ['Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'April',
                 'February', 'March', 'May', 'June']

