models: ['BiLSTM']  # 'baseline', 'linear', 'svm', 'random_forest', 'NN', 'LSTM', 'BiLSTM'
nmbr_of_runs: 1
test_only: False  # this one overwrites test
test: False
print: False

baseline:
  data_path: './data_processed/processed_data_advanced_train.pkl'
  test_path: './data_processed/processed_data_advanced_test.pkl'
  targets_path: './data_processed/baseline_targets_test.pkl'
  n_splits: 5
  seed: 4
  print: True

random_forest:
  data_path: './data_processed/processed_data_advanced_train.pkl'
  test_path: './data_processed/processed_data_advanced_test.pkl'
  n_splits: 5
  seed: 4
  print: True

linear:
  data_path: './data_processed/processed_data_advanced_train.pkl'
  test_path: './data_processed/processed_data_advanced_test.pkl'
  n_splits: 5
  seed: 4
  print: True

svm:
  data_path: './data_processed/processed_data_advanced_train.pkl'
  test_path: './data_processed/processed_data_advanced_test.pkl'
  n_splits: 5
  seed: 4
  print: True

NN:
  epochs: 200
  lr: 0.01
  momentum: 0.3
  batch_size: 32
  in_dim: 1641
  out_dim: 1
  max_norm: 5
  device: 'cuda'  # cuda, cpu
  seed: 4
  data_path: './data_processed/processed_data_advanced_train.pkl'
  test_path: './data_processed/processed_data_advanced_test.pkl'
  n_splits: 5
  print_every: 10
  print: True
  early_stopping: True
  val_len: 20

LSTM:
  epochs: 200
  lr: 0.01
  momentum: 0.0
  batch_size: 1  # This needs to be 1 because of the variable sequence lengths
  hidden: 128
  layers: 2
  in_dim: 43
  out_dim: 1
  max_norm: 5
  device: 'cuda'  # cuda, cpu
  seed: 4
  data_path: './data_processed/processed_data_basic_train.pkl'
  test_path: './data_processed/processed_data_basic_test.pkl'
  n_splits: 5
  print_every: 10
  print: True
  early_stopping: False
  val_len: 20

BiLSTM:
  epochs: 200
  lr: 0.05
  momentum: 0.5
  batch_size: 1  # This needs to be 1 because of the variable sequence lengths
  hidden: 64
  layers: 2
  in_dim: 43
  out_dim: 1
  max_norm: 5
  device: 'cuda'  # cuda, cpu
  seed: 4
  data_path: './data_processed/processed_data_basic_train.pkl'
  test_path: './data_processed/processed_data_basic_test.pkl'
  n_splits: 5
  print_every: 50
  print: True
  early_stopping: True
  val_len: 20

dataset:
  path: './data_raw/dataset_mood_smartphone.csv'
  save_folder: 'data_processed'
  seed: 42
  test_split: 0.75
  save_panda: True
  window: 5
  tsfresh_features: 'comprehensive'  # 'minimal', 'efficient', 'comprehensive'
  columns: ['mood', 'circumplex.valence']
  standard: True
  exclude_norm: ['Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'April',
                 'February', 'March', 'May', 'June']

